# Generated by Django 5.2.2 on 2025-06-25 05:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_remove_penalty_issued_on_penalty_date_issued'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='visit_date',
        ),
        migrations.AddField(
            model_name='visitor',
            name='relation',
            field=models.CharField(default='friend', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitor',
            name='visit_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
